/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfgranhotel.vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pfgranhotel.accesoDatos.*;
import pfgranhotel.entidades.*;


/**
 *
 * @author HP
 */
public class HabitacionVistas extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private DefaultTableModel modeloH;
    private HabitacionData hd;
    private TipoDeHabitacionData tpd;
    private ArrayList<TipoDeHabitacion> tha;
    private ArrayList<Habitacion> hab;
    private ReservaData res;

    public HabitacionVistas() {
        initComponents();
        hd = new HabitacionData();
        tpd = new TipoDeHabitacionData();
        res = new ReservaData();

        hab = (ArrayList<Habitacion>) hd.listarHabitaciones();
        tha = (ArrayList<TipoDeHabitacion>) tpd.listhabN();
        modelo = new DefaultTableModel();
        modeloH = new DefaultTableModel();
        armarTabla();
        cargarHabitaciones();
        armarTabla2();
        cargarHabi();
        limpiar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtHab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRlibre = new javax.swing.JRadioButton();
        jRocupada = new javax.swing.JRadioButton();
        jBsalir = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jThabi = new javax.swing.JTable();
        jCTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jbLimpiar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(1000, 862));

        jtHab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtHab);

        jLabel1.setText("Seleccione un tipo de habitacion:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Habitaciones");

        jRlibre.setText("Libre");
        jRlibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRlibreActionPerformed(evt);
            }
        });

        jRocupada.setText("Ocupada");
        jRocupada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRocupadaActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jThabi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jThabi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jThabiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jThabi);

        jCTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione el codigo de la habitacion :");

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRlibre)
                                .addComponent(jLabel1))
                            .addGap(109, 109, 109)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRocupada)))))
                .addGap(0, 395, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jBsalir)
                        .addGap(144, 144, 144)
                        .addComponent(jbLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRlibre)
                    .addComponent(jRocupada))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalir)
                    .addComponent(jbLimpiar))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRocupadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRocupadaActionPerformed
        borrarFilas2();
        jRlibre.setSelected(false);
      xTipoOcu();
    }//GEN-LAST:event_jRocupadaActionPerformed
       
       
        
    private void jRlibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRlibreActionPerformed
         borrarFilas2();
        jRocupada.setSelected(false);
       xTipoDeso();
    }//GEN-LAST:event_jRlibreActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
     dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
       borrarFilas();
        habporTipo();
       
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jThabiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jThabiAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jThabiAncestorAdded

    private void jCTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        
    }//GEN-LAST:event_jbLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<Habitacion> jCTipo;
    private javax.swing.JComboBox<TipoDeHabitacion> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRlibre;
    private javax.swing.JRadioButton jRocupada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jThabi;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JTable jtHab;
    // End of variables declaration//GEN-END:variables

    private void armarTabla() {
        ///seteamos cada columna para q aparezcan los sig titulos.
        modelo.addColumn("código");
        modelo.addColumn("cantidad de personas");
        modelo.addColumn("cantidad de camas");
        modelo.addColumn("tipos de camas");
        modelo.addColumn("precio por noche");
        jtHab.setModel(modelo);
    }

    private void borrarFilas() {
        int ind = modelo.getRowCount() - 1;
        for (int i = ind; i > -1; i--) {
            modelo.removeRow(i);
        }
    }

    private void armarTabla2() {
        ///seteamos cada columna para q aparezcan los sig titulos.
        modeloH.addColumn("Numero de habitacion");
        modeloH.addColumn("Estado de la habitacion");
        modeloH.addColumn("codigo");
        jThabi.setModel(modeloH);
    }

    private void cargarHabitaciones() {

        for (TipoDeHabitacion tip : tha) {
            jComboBox2.addItem(tip);
        }

    }
    
   

  

    private void borrarFilas2() {
        int ind = modeloH.getRowCount() - 1;
        for (int i = ind; i > -1; i--) {
            modeloH.removeRow(i);
        }
    }

    private void cargarHabi() {
        

        for (Habitacion tip : hab) {
            jCTipo.addItem(tip);
        }
     

    }



    public void habporTipo() {
        TipoDeHabitacion a = (TipoDeHabitacion) jComboBox2.getSelectedItem();
        tha = (ArrayList) tpd.obtenerHabi(a.getTipoDeHabitacion());
        for (TipoDeHabitacion tip : tha) {
            modelo.addRow(new Object[]{tip.getIdTipo(), tip.getCantPers(), tip.getCantCamas(), tip.getTipoDeCamas(), tip.getPrecio(),tip.isEstado()});
        }

    }
    
    public void xTipoDeso() {
        
        Habitacion a = (Habitacion) jCTipo.getSelectedItem();
        hab = (ArrayList) hd.obtenerhabiIdhabi(a.getIdHabitacion());
        for (Habitacion h : hab) {
            modeloH.addRow(new Object[]{h.getIdHabitacion(), h.isEstado(),h.getTipo()});
        }
    
}  
    public void xTipoOcu() {
     Habitacion a = (Habitacion) jCTipo.getSelectedItem();
        hab = (ArrayList) hd.obtenerhabiIdhabD(a.getIdHabitacion());
        for (Habitacion h : hab) {
            modeloH.addRow(new Object[]{h.getIdHabitacion(), h.isEstado(),h.getTipo()});
        }
    }
    public void limpiar(){
        jRlibre.setSelected(false);
        jRocupada.setSelected(false);
        borrarFilas();
        borrarFilas2();
        
    }
 

}